### PR TITLE
fix(share): download instead of warn

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Start seeding a file rather than warning the user they should seed the
file. Thanks! :sparkles:
- closes: https://github.com/joehand/dat-js/issues/15

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Added tests. PR now ready for review! :sparkles:

**Comment by joehand** [comment]
@yoshuawuyts I'm happy to merge this. Did y'all talk about this at all in your API discussions today?

The only reason I'm hesitant is because the user will be calling `dat.share()` and end up with `dat.download()`. This is actually why I've been thinking about a `dat.sync()` method or something that resumes a previous dat (regardless of how it was created).

**Comment by karissa** [comment]
hey @joehand!

in the older dat version (and in hyperdrive) the 'sync' function was the main command with no distinction between share and download. The distinction seems relevant, though, as 'share' implies writing to the dat, and 'download' is just updating to the latest version. This will become more relevant when we have multi-writer support.

**Comment by yoshuawuyts** [comment]
@karissa I'm confused now. From the Docs I thought it would be:
> Dat-js works the same way as the command line tool. There are two basic operations:
> - Sharing: share a directory to a key
> - Downloading: download files from a key into a directory

e.g. differentiate between "upload" and "download" - where `sync` would be both.

If that is the case, then wouldn't it make more sense to remove the `download` command from `share` (e.g. the point of this PR) and expose a third method that does both, for convenience and brevity e.g. (`dat.sync`) ? - Perhaps there's a slightly deeper problem and we should prioritize https://github.com/joehand/dat-js/issues/22 first?

**Comment by karissa** [comment]
Yeah there is probably a slightly deeper problem. I'm also pro-introducing 'sync' especially as multi-writer begins to materialize.

**Comment by karissa** [comment]
Let's solve this in the cli instead because I think the dat-js API will change

**Pull request closed without merging**
